
plugins:
  - jekyll-redirect-from
  
#-- Permalinks
permalink:        pretty

future:           true

#-- Setup
title:            TU Delft MSc Geomatics graduation thesis
description:      "Information about the TU Delft MSc Geomatics graduation thesis project (GEO2021-GEO2022), including rules, deadlines, templates, and resources for students and supervisors."
url:              "https://geomatics.bk.tudelft.nl"
baseurl:          "/geo2022"


